Algoritmo "EXE032_DESAFIO"
Var
  N: Inteiro
Inicio
  EscrevaL("------------------------------")
  EscrevaL("       TESTE SUA SORTE!")
  EscrevaL("------------------------------")
  EscrevaL
  Escreva("Digite um número de 1 a 5: ")
  Leia(N)
  EscrevaL
  Escolha N
  N <- 5
   Caso 5
      EscrevaL("Você acertou! Parabéns!")
   OutroCaso
      EscrevaL("Não foi dessa vez. Quem sabe da próxima?")
   FimEscolha
  EscrevaL
Fimalgoritmo