Algoritmo "exe008"

Var
   KM,HM,Dam,M,dm,cm,mm: real
Inicio
   Escreva("Digite uma distância em metros: ")
   Leia(M)
   KM <- M/1000
   HM <- M/100
   Dam <- M/10
   dm <- M*10
   cm <- M*100
   mm <- M*1000
   Escreval("A distância de",M,"m corresponde a:")
   Escreval(KM,"Km")
   Escreval(HM,"Hm")
   Escreval(Dam,"Dam")
   Escreval(dm,"dm")
   Escreval(cm,"cm")
   Escreval(mm,"mm")
   
Fimalgoritmo